#panels are sets of individuals for various uses
panels:
    CurratedEMHPublished:
        - WC1
        - PM1
        - Malta
        - Kolyma
        - Yana1
        - Yana2
        - Anzick
        - SalkhitArchAdm
        - Tianyuan
        - SF12
        - AfontovaGora3
        - ElMiron
        - Kostenki14Shotgun
        - Ostuni1
        - Vestonice16
        - Villabruna
        - BKF6620
        - BKCC7335
        - BKBB7240
        - BK1653
        - LBK
        - Loschbour
        - UstIshim
        - Vestonice13
        - Vestonice43
        - MotaHC
        - OaseNew
        - SunghirIII
        - Sumidouro5
        - SpiritCave
        - SunghirI
        - SunghirII
        - SunghirIV
        - LeangPanninge
        - Bichon
        - Satsurblia
        - KK1
        - ZVEJ25
        - ZVEJ31
        - NE5
        - Karelia
        - ZlatyKunShotgun
        - NE1
        - LaBrana
        - R15
        - R7
        - R11
        - AfanasievoMother
        - AfanasievoSon1
        - AfanasievoFather
        - AfanasievoSon2
        - CNE1
        - KS20KS25
        - KM4
        - R2R7
        - KS5
        - M2113
        - M368
        - SanTeodoro3
    PresentDaySGDP:
        - B_Australian-3
        - B_Australian-4
        - B_Crete-1
        - B_Crete-2
        - B_Dai-4
        - B_Dinka-3
        - B_French-3
        - B_Han-3
        - B_Ju_hoan_North-4
        - B_Karitiana-3
        - B_Mandenka-3
        - B_Mbuti-4
        - B_Mixe-1
        - B_Papuan-15
        - B_Sardinian-3
        - B_Yoruba-3
        - S_Abkhasian-1
        - S_Abkhasian-2
        - S_Adygei-1
        - S_Adygei-2
        - S_Albanian-1
        - S_Aleut-1
        - S_Aleut-2
        - S_Altaian-1
        - S_Ami-1
        - S_Ami-2
        - S_Armenian-1
        - S_Armenian-2
        - S_Atayal-1
        - S_Balochi-1
        - S_Balochi-2
        - S_BantuHerero-1
        - S_BantuHerero-2
        - S_BantuKenya-1
        - S_BantuKenya-2
        - S_BantuTswana-1
        - S_BantuTswana-2
        - S_Basque-1
        - S_Basque-2
        - S_BedouinB-1
        - S_BedouinB-2
        - S_Bengali-1
        - S_Bengali-2
        - S_Bergamo-1
        - S_Bergamo-2
        - S_Biaka-1
        - S_Biaka-2
        - S_Bougainville-1
        - S_Bougainville-2
        - S_Brahmin-1
        - S_Brahmin-2
        - S_Brahui-1
        - S_Brahui-2
        - S_Bulgarian-1
        - S_Bulgarian-2
        - S_Burmese-1
        - S_Burmese-2
        - S_Burusho-1
        - S_Burusho-2
        - S_Cambodian-1
        - S_Cambodian-2
        - S_Chane-1
        - S_Chechen-1
        - S_Chukchi-1
        - S_Czech-2
        - S_Dai-1
        - S_Dai-2
        - S_Dai-3
        - S_Daur-2
        - S_Dinka-1
        - S_Dinka-2
        - S_Druze-1
        - S_Druze-2
        - S_Dusun-1
        - S_Dusun-2
        - S_English-1
        - S_English-2
        - S_Esan-1
        - S_Esan-2
        - S_Eskimo_Chaplin-1
        - S_Eskimo_Naukan-1
        - S_Eskimo_Naukan-2
        - S_Eskimo_Sireniki-1
        #- S_Eskimo_Sireniki-2
        - S_Estonian-1
        - S_Estonian-2
        - S_Even-1
        - S_Even-2
        - S_Even-3
        - S_Finnish-1
        - S_Finnish-2
        - S_Finnish-3
        - S_French-1
        - S_French-2
        - S_Gambian-1
        - S_Gambian-2
        - S_Georgian-1
        - S_Georgian-2
        - S_Greek-1
        - S_Greek-2
        - S_Han-1
        - S_Han-2
        - S_Hawaiian-1
        - S_Hazara-1
        - S_Hazara-2
        - S_Hezhen-1
        - S_Hezhen-2
        - S_Hungarian-1
        - S_Hungarian-2
        - S_Icelandic-1
        - S_Icelandic-2
        - S_Igorot-1
        - S_Igorot-2
        - S_Iranian-1
        - S_Iranian-2
        - S_Iraqi_Jew-1
        - S_Iraqi_Jew-2
        - S_Irula-1
        - S_Irula-2
        - S_Itelman-1
        - S_Japanese-1
        - S_Japanese-2
        - S_Japanese-3
        - S_Jordanian-1
        - S_Jordanian-2
        - S_Jordanian-3
        - S_Ju_hoan_North-1
        - S_Ju_hoan_North-2
        - S_Ju_hoan_North-3
        - S_Kalash-1
        - S_Kalash-2
        - S_Kapu-1
        - S_Kapu-2
        - S_Karitiana-1
        - S_Karitiana-2
        - S_Khomani_San-1
        - S_Khomani_San-2
        - S_Khonda_Dora-1
        - S_Kinh-1
        - S_Kinh-2
        - S_Korean-1
        - S_Korean-2
        - S_Kusunda-1
        - S_Kusunda-2
        - S_Kyrgyz-1
        - S_Kyrgyz-2
        - S_Lahu-1
        - S_Lahu-2
        - S_Lezgin-1
        - S_Lezgin-2
        - S_Luhya-1
        - S_Luhya-2
        - S_Luo-1
        - S_Luo-2
        - S_Madiga-1
        - S_Madiga-2
        - S_Makrani-1
        - S_Makrani-2
        - S_Mala-2
        - S_Mala-3
        - S_Mandenka-1
        - S_Mandenka-2
        - S_Mansi-1
        - S_Mansi-2
        - S_Maori-1
        - S_Masai-1
        - S_Masai-2
        - S_Mayan-1
        - S_Mayan-2
        - S_Mbuti-1
        - S_Mbuti-2
        - S_Mbuti-3
        - S_Mende-1
        - S_Mende-2
        - S_Miao-1
        - S_Miao-2
        - S_Mixe-2
        - S_Mixtec-1
        - S_Mixtec-2
        - S_Mongola-1
        - S_Mongola-2
        - S_Mozabite-1
        - S_Mozabite-2
        - S_Naxi-1
        - S_Naxi-3
        - S_North_Ossetian-1
        - S_North_Ossetian-2
        - S_Norwegian-1
        - S_Orcadian-1
        - S_Orcadian-2
        - S_Oroqen-1
        - S_Oroqen-2
        - S_Palestinian-1
        - S_Palestinian-2
        - S_Palestinian-3
        - S_Papuan-1
        - S_Papuan-10
        - S_Papuan-11
        - S_Papuan-13
        - S_Papuan-14
        - S_Papuan-2
        - S_Papuan-3
        - S_Papuan-4
        - S_Papuan-5
        - S_Papuan-6
        - S_Papuan-7
        - S_Papuan-8
        - S_Papuan-9
        - S_Pathan-1
        - S_Pathan-2
        - S_Piapoco-1
        - S_Piapoco-2
        - S_Pima-1
        - S_Pima-2
        - S_Polish-1
        - S_Punjabi-1
        - S_Punjabi-2
        - S_Punjabi-3
        - S_Punjabi-4
        - S_Quechua-1
        - S_Quechua-2
        - S_Quechua-3
        - S_Relli-1
        - S_Relli-2
        - S_Russian-1
        - S_Russian-2
        - S_Saami-1
        - S_Saami-2
        - S_Saharawi-1
        - S_Saharawi-2
        - S_Samaritan-1
        - S_Sardinian-1
        - S_Sardinian-2
        - S_She-1
        - S_She-2
        - S_Sindhi-1
        - S_Sindhi-2
        - S_Somali-1
        - S_Spanish-1
        - S_Spanish-2
        - S_Surui-1
        - S_Surui-2
        - S_Tajik-1
        - S_Tajik-2
        - S_Thai-1
        - S_Thai-2
        - S_Tlingit-1
        - S_Tlingit-2
        - S_Tu-1
        - S_Tu-2
        - S_Tubalar-1
        - S_Tubalar-2
        - S_Tujia-1
        - S_Tujia-2
        - S_Turkish-1
        - S_Turkish-2
        - S_Tuscan-1
        - S_Tuscan-2
        - S_Ulchi-1
        - S_Ulchi-2
        - S_Uygur-1
        - S_Uygur-2
        - S_Xibo-1
        - S_Xibo-2
        - S_Yadava-1
        - S_Yadava-2
        - S_Yakut-1
        - S_Yakut-2
        - S_Yemenite_Jew-1
        - S_Yemenite_Jew-2
        - S_Yi-1
        - S_Yi-2
        - S_Yoruba-1
        - S_Yoruba-2
        - S_Zapotec-1
        - S_Zapotec-2
